{
 "title": "Stock Data Visualization",
 "time": { "from": "2022-05-01T06:54:47.190Z", "to": "2022-07-01T22:56:39.955Z" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "main_ticker",
    "label": "main_ticker",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"market_data\",\n    tag: \"ticker\",\n    predicate: (r) => true,\n    start: -365d\n)"
   },
   {
    "name": "compare_ticker",
    "label": "Ticker to compare with main_ticker",
    "query": "import \"influxdata/influxdb/v1\"\nv1.tagValues(\n    bucket: \"market_data\",\n    tag: \"ticker\",\n    predicate: (r) => true,\n    start: -365d\n)"
   },
   {
    "name": "technical_indicator",
    "query": "\"MA20\", \"MA50\", \"RSI\", \"close\", \"EMA12\", \"EMA26\""
   }
  ]
 },
 "panels": [
  {
   "title": "Candlestick chart",
   "type": "candlestick",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"market_data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"stock_info\" and\n    r.ticker == \"${main_ticker}\" \n  )\n  |> filter(fn: (r) => r[\"_field\"] == \"EMA12\" or r[\"_field\"] == \"EMA26\" or r[\"_field\"] == \"MA20\" or r[\"_field\"] == \"MA50\" or r[\"_field\"] == \"close\" or r[\"_field\"] == \"high\" or r[\"_field\"] == \"low\" or r[\"_field\"] == \"open\" or r[\"_field\"] == \"volume\")\n  "
    }
   ]
  },
  {
   "title": "RSI",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"market_data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"stock_info\" and\n    r._field == \"RSI\" and\n    r.ticker == \"${main_ticker}\"\n  )\n\n\n\n  "
    }
   ]
  },
  {
   "title": "Price",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"market_data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"stock_info\" and\n    (r._field == \"close\" or r._field == \"MA20\" or r._field == \"MA50\") and\n    r.ticker == \"${main_ticker}\"\n  )\n\n\n\n  "
    }
   ]
  },
  {
   "title": "MACD",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"market_data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"stock_info\" and\n    r.ticker == \"${main_ticker}\" and\n    (r._field == \"MACD\" or r._field == \"SIGNAL_LINE\")\n  )\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> map(fn: (r) => ({\n    r with\n    vol: r.MACD - r.SIGNAL_LINE,\n   }))\n\n  "
    }
   ]
  },
  {
   "title": "Compare stocks",
   "type": "timeseries",
   "description": "Compare ${technical_indicator} of two stock ${main_ticker} and ${compare_ticker}  ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"market_data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"stock_info\" and\n    r._field == ${technical_indicator} and\n    r.ticker == \"${main_ticker}\"\n  )"
    },
    {
     "query": "from(bucket: \"market_data\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"stock_info\" and\n    r._field == ${technical_indicator} and\n    r.ticker == \"${compare_ticker}\"\n  )"
    }
   ]
  }
 ]
}